# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EsaCli < Formula
  desc "CLI tool for managing esa.io articles"
  homepage "https://github.com/shellme/esa-cli"
  version "0.2.7"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/shellme/esa-cli/releases/download/v0.2.7/esa-cli_0.2.7_darwin_amd64.tar.gz"
      sha256 "e2de85abdfc746ff3a81354d6c7ab6b6cf9ef2f08147f38f52346031745ff15b"

      def install
        bin.install "esa-cli"
      end
    end
    on_arm do
      url "https://github.com/shellme/esa-cli/releases/download/v0.2.7/esa-cli_0.2.7_darwin_arm64.tar.gz"
      sha256 "3b4955c5b0bf8705fa385ec971752c6f8b64f4a81ca5acf4b62f6ac937d8afa0"

      def install
        bin.install "esa-cli"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/shellme/esa-cli/releases/download/v0.2.7/esa-cli_0.2.7_linux_amd64.tar.gz"
        sha256 "d88dff3f9fdadd71e88e2ca46a1b61aa43eb1116b27750536c6d85eb039578dc"

        def install
          bin.install "esa-cli"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/shellme/esa-cli/releases/download/v0.2.7/esa-cli_0.2.7_linux_arm64.tar.gz"
        sha256 "9c06c37f2697f1284c20c4c967d8bb2cb2070ae700ca71b6280a656698560ca3"

        def install
          bin.install "esa-cli"
        end
      end
    end
  end

  test do
    system "#{bin}/esa-cli", "version"
  end
end
