# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EsaCli < Formula
  desc "CLI tool for managing esa.io articles"
  homepage "https://github.com/shellme/esa-cli"
  version "0.2.4"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/shellme/esa-cli/releases/download/v0.2.4/esa-cli_0.2.4_darwin_amd64.tar.gz"
      sha256 "99e714fdfa6445912efd36cda363eab3781e9075165faca390e37305514cb274"

      def install
        bin.install "esa-cli"
      end
    end
    on_arm do
      url "https://github.com/shellme/esa-cli/releases/download/v0.2.4/esa-cli_0.2.4_darwin_arm64.tar.gz"
      sha256 "ff5f8b572257b92b58db45d3eea499d2094c5984f9df120dc717753e0521009b"

      def install
        bin.install "esa-cli"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/shellme/esa-cli/releases/download/v0.2.4/esa-cli_0.2.4_linux_amd64.tar.gz"
        sha256 "b551ebe04d8ca49eb23c562a993d860ce6f8f730320142487e9ed31c53b70908"

        def install
          bin.install "esa-cli"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/shellme/esa-cli/releases/download/v0.2.4/esa-cli_0.2.4_linux_arm64.tar.gz"
        sha256 "31bca7954cc4c15024ff6c2a19daa01f6b267434072f97cad89ec380d6452a56"

        def install
          bin.install "esa-cli"
        end
      end
    end
  end

  test do
    system "#{bin}/esa-cli", "version"
  end
end
