# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EsaCli < Formula
  desc "CLI tool for managing esa.io articles"
  homepage "https://github.com/shellme/esa-cli"
  version "0.2.9"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/shellme/esa-cli/releases/download/v0.2.9/esa-cli_0.2.9_darwin_arm64.tar.gz"
      sha256 "65918a8c63a34f129b0d5ee3ad0a863839aeb34b1ad1537bf89ea2b08c766f3a"

      def install
        bin.install "esa-cli"
      end
    end
    on_arm do
      url "https://github.com/shellme/esa-cli/releases/download/v0.2.9/esa-cli_0.2.9_darwin_arm64.tar.gz"
      sha256 "df068f89f536c5eab7056dc9af800922718f02129881381591393d523d011bd9"

      def install
        bin.install "esa-cli"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/shellme/esa-cli/releases/download/v0.2.9/esa-cli_0.2.9_darwin_arm64.tar.gz"
        sha256 "b9043a5a0193aead8189eed8d32bae93d38f119294e003bdca7cc0a7508f409c"

        def install
          bin.install "esa-cli"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/shellme/esa-cli/releases/download/v0.2.9/esa-cli_0.2.9_darwin_arm64.tar.gz"
        sha256 "97178fd0c41c56385246a3aa9b9d9af3ed34a668255f88cb48e4e2c32be81ba2"

        def install
          bin.install "esa-cli"
        end
      end
    end
  end

  test do
    system "#{bin}/esa-cli", "version"
  end
end
